//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInformation.App.PhoneService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumberByIdModel", Namespace="http://schemas.datacontract.org/2004/07/CustomerInformation.Models.Phones")]
    [System.SerializableAttribute()]
    public partial class PhoneNumberByIdModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneService.IPhoneService")]
    public interface IPhoneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/GetHomePhoneNumberById", ReplyAction="http://tempuri.org/IPhoneService/GetHomePhoneNumberByIdResponse")]
        CustomerInformation.App.PhoneService.PhoneNumberByIdModel GetHomePhoneNumberById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/GetHomePhoneNumberById", ReplyAction="http://tempuri.org/IPhoneService/GetHomePhoneNumberByIdResponse")]
        System.Threading.Tasks.Task<CustomerInformation.App.PhoneService.PhoneNumberByIdModel> GetHomePhoneNumberByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/GetOfficePhoneNumberById", ReplyAction="http://tempuri.org/IPhoneService/GetOfficePhoneNumberByIdResponse")]
        CustomerInformation.App.PhoneService.PhoneNumberByIdModel GetOfficePhoneNumberById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/GetOfficePhoneNumberById", ReplyAction="http://tempuri.org/IPhoneService/GetOfficePhoneNumberByIdResponse")]
        System.Threading.Tasks.Task<CustomerInformation.App.PhoneService.PhoneNumberByIdModel> GetOfficePhoneNumberByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneServiceChannel : CustomerInformation.App.PhoneService.IPhoneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneServiceClient : System.ServiceModel.ClientBase<CustomerInformation.App.PhoneService.IPhoneService>, CustomerInformation.App.PhoneService.IPhoneService {
        
        public PhoneServiceClient() {
        }
        
        public PhoneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomerInformation.App.PhoneService.PhoneNumberByIdModel GetHomePhoneNumberById(int id) {
            return base.Channel.GetHomePhoneNumberById(id);
        }
        
        public System.Threading.Tasks.Task<CustomerInformation.App.PhoneService.PhoneNumberByIdModel> GetHomePhoneNumberByIdAsync(int id) {
            return base.Channel.GetHomePhoneNumberByIdAsync(id);
        }
        
        public CustomerInformation.App.PhoneService.PhoneNumberByIdModel GetOfficePhoneNumberById(int id) {
            return base.Channel.GetOfficePhoneNumberById(id);
        }
        
        public System.Threading.Tasks.Task<CustomerInformation.App.PhoneService.PhoneNumberByIdModel> GetOfficePhoneNumberByIdAsync(int id) {
            return base.Channel.GetOfficePhoneNumberByIdAsync(id);
        }
    }
}
